name: Build OpenWrt for CMCC XR30

on: 
  workflow_dispatch:
    inputs:
      target:
        description: 'mediatek_mt7981'
        required: true
        default: 'mediatek_mt7981'

env:
 
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build 
    
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang flex bison g++ gawk \
        gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
        python3-setuptools rsync swig unzip zlib1g-dev file wget \
        llvm python3-pyelftools libpython3-dev ccache \
        libelf-dev device-tree-compiler

    - name: Clone OpenWrt source
      run: |
        git clone https://github.com/openwrt/openwrt.git -b openwrt-24.10
        cd openwrt
        # 应用您的 XR30 DTS 修改
        cp -r $GITHUB_WORKSPACE/devices/mediatek_mt7981/* .

    - name: Configure build
      run: |
        cd openwrt
        make defconfig
        # 应用 XR30 专属配置
        cat devices/mediatek_mt7981/config_xr30 >> .config
        make defconfig

    - name: Compile firmware
      run: |
        cd openwrt
        echo "Using $(nproc) threads for compilation"
        make -j$(nproc) || make V=s

    - name: Prepare release assets
      run: |
        cd openwrt/bin/targets/*/*
        mkdir -p release_assets
        cp *sysupgrade.bin release_assets/
        cp *factory.bin release_assets/
        cp $GITHUB_WORKSPACE/openwrt/.config release_assets/xr30.config
        echo "CMCC XR30 $(date +'%Y-%m-%d')" > release_assets/release_notes.txt

    - name: Create release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: xr30-$(date +'%Y%m%d-%H%M')
        name: "CMCC XR30 $(date +'%Y-%m-%d')"
        body: "Automated build for CMCC XR30 with custom DTS"
        files: openwrt/bin/targets/*/*/release_assets/*
